//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autorunner {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    partial class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autorunner.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon Main {
            get {
                object obj = ResourceManager.GetObject("Main", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }

        private void InitializeComponent()
        {
            panelAutorunTaskItems = new FlowLayoutPanel();
            buttonAddAutorun = new Button();
            SuspendLayout();
            // 
            // panelAutorunTaskItems
            // 
            panelAutorunTaskItems.AutoScroll = true;
            panelAutorunTaskItems.Dock = DockStyle.Top;
            panelAutorunTaskItems.FlowDirection = FlowDirection.TopDown;
            panelAutorunTaskItems.Location = new Point(0, 47);
            panelAutorunTaskItems.Margin = new Padding(3, 4, 3, 4);
            panelAutorunTaskItems.Name = "panelAutorunTaskItems";
            panelAutorunTaskItems.Size = new Size(590, 701);
            panelAutorunTaskItems.TabIndex = 0;
            // 
            // buttonAddAutorun
            // 
            buttonAddAutorun.Dock = DockStyle.Top;
            buttonAddAutorun.Location = new Point(0, 0);
            buttonAddAutorun.Margin = new Padding(3, 4, 3, 4);
            buttonAddAutorun.Name = "buttonAddAutorun";
            buttonAddAutorun.Size = new Size(590, 47);
            buttonAddAutorun.TabIndex = 1;
            buttonAddAutorun.Text = "Додати автозапуск";
            buttonAddAutorun.UseVisualStyleBackColor = true;
            buttonAddAutorun.Click += AddAutorun_Click;
            // 
            // MainForm
            // 
            AutoScaleMode = AutoScaleMode.None;
            ClientSize = new Size(590, 748);
            Controls.Add(panelAutorunTaskItems);
            Controls.Add(buttonAddAutorun);
            Margin = new Padding(3, 4, 3, 4);
            Name = "MainForm";
            Text = "Autorunner";
            Resize += MainForm_Resize;
            ResumeLayout(false);
        }

        private System.Windows.Forms.FlowLayoutPanel panelAutorunTaskItems;
        private System.Windows.Forms.Button buttonAddAutorun;
    }
}
